DROP TABLE IF EXISTS tasks_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS tasks_relations;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS colour_themes;
